config_dict = dict(
    # SPARK
    # SPARK_DEFAULT_BROADCAST_TIMEOUT= 1000,
    # SPARK_DEFAULT_AUTO_BROADCAST_JOIN_THRESHOLD= 20000000,
    # SPARK_DEFAULT_NETWORK_TIMEOUT= "900s",
    SPARK_DEFAULT_ARROW=False,

    CONFIG_SPARK_SIZE_L=dict(
        SPARK_APPLICATION_NAME="SCRIPTS_CRM_SIZE_L",
        SPARK_DEFAULT_EXECUTORS_MEMORY="10g",
        SPARK_DEFAULT_DRIVER_MEMORY="6g",
        SPARK_DEFAULT_EXECUTOR_CORES=4,
        SPARK_DEFAULT_DRIVER_CORES=4),
    CONFIG_SPARK_SIZE_M=dict(
        SPARK_APPLICATION_NAME="SCRIPTS_CRM_SIZE_M",
        SPARK_DEFAULT_EXECUTORS_MEMORY="5g",
        SPARK_DEFAULT_DRIVER_MEMORY="3g",
        SPARK_DEFAULT_EXECUTOR_CORES=2,
        SPARK_DEFAULT_DRIVER_CORES=1),

    # LOGGER
    LOG_FILENAME="PROJECT_DATALAKE",
    LOGGER_PREFIX="PROJECT_DATALAKE",
    LOGGER_PATH="./logs",
    LOGGER_PATH_TEST="./logs/test",
    LOG_FORMAT="%(asctime)s\t%(name)s\t%(levelname)s\t%(message)s",

)
